key_name             = "demo-ec2-key"
instance_type        = "t2.micro"
aws_region           = "ap-south-1"
name                 = "prod-instance"
security_group_name  = "tf-my-ec2-sec-grp"
subnet               = "subnet-03368a95527b7c160"
