version: 0.2

env: 
  variables:
    CODE_SRC_DIR: "."
    # TF_VERSION: "1.3.7"

phases:
  install: 
    runtime-versions: 
      python: "3.12"
    commands:
      - "yum install -y yum-utils shadow-utils"
      - "yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo"
      - "yum -y install terraform"

  build:
    commands: 
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "terraform init"
      - "echo ## TERRAFORM PLAN : Strated with terraform apply"
      - "terraform plan -input=false"

artifacts:
  files: 
    - '**/*'       
      