version: 0.2

env:
  Variables:
    CODE_SRC_DIR: "."
    # TF_VERSION: "1.6.4"

phases:
  install: 
    runtime-versions: 
      python: "3.12"
    commands:
      - "yum install -y yum-utils shadow-utils"
      - "yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo"
      - "yum -y install terraform"
  build:
    commands: 
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "terraform init"
      - "echo ## TERRAFORM PLAN : Generate the terraform plan"
      - "terraform plan -out tfapply"

artifacts:
  files: 
    - '**/*'       

